project:
  type: website
  output-dir: docs

website:
  title: "Samantha Csik"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - resources.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css

editor: visual

